# Build specification for building project under Amazon CodeBuild

version: 0.1
#environment_variables:
#  plaintext:
phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install curl
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - sudo apt-get install -y nodejs
  pre_build:
    commands:
      - $(aws ecr get-login)
  build:
    commands:
      - docker run --rm -v "$PWD":/app trion/ng-cli-e2e /bin/bash -c "npm install && npm run test:e2e:ci -- --base-href $ENDPOINT_URI"
  post_build:
    commands:
      - aws s3 cp --recursive --quiet --acl public-read ./screenshots ${SCREENSHOTS_BUCKET}/

