{{- if .Values.service.hostName }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
    {{- if .Values.service.authUrl }}
    ingress.kubernetes.io/auth-url: {{ .Values.service.authUrl }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.service.hostName | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end }}
{{- if .Values.service.publicHostName }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-pub
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - host: {{ .Values.service.publicHostName | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end }}
