const CONSTANTS = {
  ATTRS: 'attrs',
  COLLAPSED: 'collapsed',
  COLLAPSED_AUTOMATICALLY: 'collapsedAutomatically',
  COLOR: 'color',
  CONNECTED: 'connected',
  DEPTH: 'depth',
  FIXED: 'fixed',
  FX: 'fx',
  FY: 'fy',
  GRAVITY_POINT: 'gravityPoint',
  HIDDEN: 'hidden',
  HIDDEN_BY_FILTERS: 'hiddenByFilters',
  ID: 'id',
  INDEX: 'index',
  NAME: 'name',
  RADIUS: 'radius',
  SIZE: 'size',
  SX: 'sx',
  SY: 'sy',
  TYPE: 'type',
  WEIGHT: 'weight',
  X: 'x',
  Y: 'y',
  _COLOR: '_color',
  _SIZE: '_size',
};

export default Object.freeze(CONSTANTS);
