const CONSTANTS = {
  ADDING_GRAVITY_POINTS: 'addingGravityPoints',
  COPIED_NODE_ID: 'copiedNodeId',
  CURRENT_EVENT: 'currentEvent',
  CURRENT_NODE: 'currentNode',
  CURRENT_VIEW_NAME: 'currentViewName',
  EDIT_TWIGLET_MODEL: 'editTwigletModel',
  EVENT_FILTER_TEXT: 'eventFilterText',
  FORM_VALID: 'formValid',
  HIGHLIGHTED_NODE: 'highlightedNode',
  IS_EDITING: 'isEditing',
  IS_EDITING_GRAVITY: 'isEditingGravity',
  IS_EDITING_VIEW: 'isEditingView',
  IS_PLAYING_BACK: 'isPlayingBack',
  IS_SIMIULATING: 'isSimulating',
  LEVEL_FILTER_MAX: 'levelFilterMax',
  MODE: 'mode',
  NODE_TYPE_TO_BE_ADDED: 'nodeTypeToBeAdded',
  PING: 'ping',
  PLAYBACK_INTERVAL: 'playbackInterval',
  TEXT_TO_FILTER_ON: 'textToFilterOn',
  USER: 'user',
};

export default Object.freeze(CONSTANTS);
