const CONSTANTS = {
  ADDING_GRAVITY_POINTS: 'addingGravityPoints',
  ALPHA_TARGET: 'alphaTarget',
  AUTO_CONNECTIVITY: 'autoConnectivity',
  CASCADING_COLLAPSE: 'cascadingCollapse',
  COLLISION_DISTANCE: 'collisionDistance',
  COPIED_NODE_ID: 'copiedNodeId',
  CURRENT_EVENT: 'currentEvent',
  CURRENT_NODE: 'currentNode',
  CURRENT_VIEW_NAME: 'currentViewName',
  EDIT_TWIGLET_MODEL: 'editTwigletModel',
  EVENT_FILTER_TEXT: 'eventFilterText',
  FILTERS: 'filters',
  FORCE_CHARGE_STRENGTH: 'forceChargeStrength',
  FORCE_GRAVITY_X: 'forceGravityX',
  FORCE_GRAVITY_Y: 'forceGravityY',
  FORCE_LINK_DISTANCE: 'forceLinkDistance',
  FORCE_LINK_STRENGTH: 'forceLinkStrength',
  FORCE_VELOCITY_DECAY: 'forceVelocityDecay',
  FORM_VALID: 'formValid',
  GRAVITY_POINTS: 'gravityPoints',
  HIGHLIGHTED_NODE: 'highlightedNode',
  IS_EDITING: 'isEditing',
  IS_EDITING_GRAVITY: 'isEditingGravity',
  IS_PLAYING_BACK: 'isPlayingBack',
  IS_SIMIULATING: 'isSimulating',
  LEVEL_FILTER: 'levelFilter',
  LEVEL_FILTER_MAX: 'levelFilterMax',
  LINK_TYPE: 'linkType',
  MODE: 'mode',
  NODE_TYPE_TO_BE_ADDED: 'nodeTypeToBeAdded',
  PING: 'ping',
  PLAYBACK_INTERVAL: 'playbackInterval',
  RENDER_ON_EVERY_TICK: 'renderOnEveryTick',
  RUN_SIMULATION: 'runSimulation',
  SCALE: 'scale',
  SEPARATION_DISTANCE: 'separationDistance',
  SHOW_LINK_LABELS: 'showLinkLabels',
  SHOW_NODE_LABELS: 'showNodeLabels',
  TEXT_TO_FILTER_ON: 'textToFilterOn',
  TRAVERSE_DEPTH: 'traverseDepth',
  TREE_MODE: 'treeMode',
  USER: 'user',
};

export default Object.freeze(CONSTANTS);
